apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ template "rocketchat.fullname" . }}
spec:
  routes:
  - enableWebsockets: true
    match: /
    services:
    - name: {{ template "rocketchat.fullname" . }}
      port: {{ .Values.service.port }}
  virtualhost:
    fqdn: {{ .Values.host }}
    tls:
      secretName: rocketchat-tls-secret
